### ISSUE TITLE
Is it possible to use it with single files?

### ISSUE THREAD

**Issue by resolritter** [hyotang666/trivial-formatter#2]
Hello. I am very much a beginner in Common Lisp, so I'm feeling a bit helpless on how to use this project.

I would like to format a single ECL file from the command line. Something like:

```
sbcl --non-interactive --load formatter.lisp --eval '(fmt "/program/main.lisp")'
```

By "format" I mean automatically indent the code in a nice style and print the source standard output. I am not sure if this is what this package does, exactly.

I tried to read the code, but couldn't find how to do this. My guess related to this line:

https://github.com/hyotang666/trivial-formatter/blob/2fbf05bb15de103546ba3630d59e913ab2f26ef1/src/trivial-formatter.lisp#L71

Is that it's not possible to format a single file. Is there some workaround I could try?

Thanks in advance!

**Comment by hyotang666** [comment]
Hi. 

> By "format" I mean automatically indent the code in a nice style and print the source standard output. 

Yes. It is what trivial-formatter do.
Please see [trivial-formatter's source code](https://github.com/hyotang666/trivial-formatter/blob/master/src/trivial-formatter.lisp).
This file is formatted by trivial-formatter itself.

> Is that it's not possible to format a single file. Is there some workaround I could try?

Trivial-formatter is designed to format [asdf:system](https://www.common-lisp.net/project/asdf/), not for single lisp file.

> ASDF is the de facto standard build facility for Common Lisp.
> Your Lisp implementation probably contains a copy of ASDF.

To install trivial-formatter, [roswell](https://github.com/roswell/roswell) is recommended.

> Roswell is a Lisp implementation installer/manager, launcher, and much more!

How to install roswell is [here](https://github.com/roswell/roswell/wiki/Installation).

After installing roswell, you can install trivial-formatter with command below.

```
ros install hyotang666/trivial-formatter
```

To launch lisp implementation with roswell is 

```
ros run
```

To load trivial-formatter to running lisp environment, evaluate expression below in the repl.

```
(ql:quickload :trivial-formatter)
```

To format single lisp file, you need help of asdf object as intermidiate object.
Repl interaction will be like below.

```
* (load "your-lisp-file")
T

* (make-instance 'asdf:cl-source-file :name :dummy)
#<ASDF/LISP-ACTION:CL-SOURCE-FILE :DUMMY>

* (setf (slot-value * 'asdf/component::absolute-pathname) "your-lisp-file")
"your-lisp-file"

* (trivial-formatter::debug-printer **)
```

**Comment by resolritter** [comment]
Thanks for the response! I saw that you updated the README already as well, so I think it's fine.
